### ISSUE TITLE
Help with accuracy improvement.

### ISSUE THREAD

**Issue by otaviopl** [carlosplf/tf-cats-and-dogs#1]
Help for a 99% of accuracy.

**Comment by carlosplf** [comment]
Hey @otaviopl, the _main_ branch now has all the work from the past weeks. This includes:

- Lots of refactoring;
- The original VGG16 model, alongside with our Custom model.
- An API to call the CNN training and predicting;
- A frontend Webpage built with React so the users can submit images for classification;

Accuracy is way higher, but not 99% yet. We must be somewhere close to 92%, which is awesome! 😄 

I'm closing this Issue for now.

**Comment by carlosplf** [comment]
Just for documentation... The VGG16 model was the best, and achieved an accuracy of 92%.

<img width="610" alt="Screenshot 2023-05-03 at 14 50 33" src="https://user-images.githubusercontent.com/4533133/236002534-cf2f601e-85f9-4a17-9869-9cd955034fb1.png">
